name: hello 

on: 
   push: 
     branches: ["main"]
     paths: '**.md'
   workflow_dispatch:

jobs: 
  hello: 
    runs-on: ubuntue-latest
    steps: 
      - name: hello 
        run: echo "hello "
