name: hello 

env: 
   NAME1: 'workflow'


on: 
   push: 
   workflow_dispatch:

jobs: 
  hello: 
    env: 
      NAME: 'build'
    runs-on: ubuntue-latest
    steps: 
      - name: hello 
        run: echo "hello ${{ env.NAME1 }} $NAME1"
